// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurJRAmr-p97KUKOKImticmZl3YgVAEj8',
    appId: '1:1065461333787:web:cf6ce3bb685112ac011dbe',
    messagingSenderId: '1065461333787',
    projectId: 'tontine-ecd64',
    authDomain: 'tontine-ecd64.firebaseapp.com',
    storageBucket: 'tontine-ecd64.firebasestorage.app',
    measurementId: 'G-ZP8VHFMMYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyv5Dos_J5k2yuKefI3sK2gfEFXkb0nY',
    appId: '1:1065461333787:android:3548a2c027cc2931011dbe',
    messagingSenderId: '1065461333787',
    projectId: 'tontine-ecd64',
    storageBucket: 'tontine-ecd64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgrg5O7pvVOYZM9AtonZLzwzHKZsQUas',
    appId: '1:1065461333787:ios:bc323ec78d4f4554011dbe',
    messagingSenderId: '1065461333787',
    projectId: 'tontine-ecd64',
    storageBucket: 'tontine-ecd64.firebasestorage.app',
    iosBundleId: 'com.example.maTontine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgrg5O7pvVOYZM9AtonZLzwzHKZsQUas',
    appId: '1:1065461333787:ios:bc323ec78d4f4554011dbe',
    messagingSenderId: '1065461333787',
    projectId: 'tontine-ecd64',
    storageBucket: 'tontine-ecd64.firebasestorage.app',
    iosBundleId: 'com.example.maTontine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBurJRAmr-p97KUKOKImticmZl3YgVAEj8',
    appId: '1:1065461333787:web:4c91fe8a2f51053f011dbe',
    messagingSenderId: '1065461333787',
    projectId: 'tontine-ecd64',
    authDomain: 'tontine-ecd64.firebaseapp.com',
    storageBucket: 'tontine-ecd64.firebasestorage.app',
    measurementId: 'G-Y1XJ0R74DH',
  );
}
